name: hierro_flutter
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/logoH.png


  uses-material-design: true

  